name: deploy

on:
  push:
    branches: [main]

jobs:
  workflow-check:
    uses: ./.github/workflows/workflow-syntax-check.yml
  workflow-build:
    uses: ./.github/workflows/workflow-build.yml

  gh-release:
    needs: [workflow-build]
    name: 'Deploy website'
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
    - name: Publish
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/
